//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BuspasManager.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SAE_TEMP_BKEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SAE_TEMP_BKEntities object using the connection string found in the 'SAE_TEMP_BKEntities' section of the application configuration file.
        /// </summary>
        public SAE_TEMP_BKEntities() : base("name=SAE_TEMP_BKEntities", "SAE_TEMP_BKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAE_TEMP_BKEntities object.
        /// </summary>
        public SAE_TEMP_BKEntities(string connectionString) : base(connectionString, "SAE_TEMP_BKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SAE_TEMP_BKEntities object.
        /// </summary>
        public SAE_TEMP_BKEntities(EntityConnection connection) : base(connection, "SAE_TEMP_BKEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<intfStops> intfStops
        {
            get
            {
                if ((_intfStops == null))
                {
                    _intfStops = base.CreateObjectSet<intfStops>("intfStops");
                }
                return _intfStops;
            }
        }
        private ObjectSet<intfStops> _intfStops;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the intfStops EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTointfStops(intfStops intfStops)
        {
            base.AddObject("intfStops", intfStops);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SAE_TEMP_BKModel", Name="intfStops")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class intfStops : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new intfStops object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="stopId">Initial value of the StopId property.</param>
        /// <param name="stopIdNum">Initial value of the StopIdNum property.</param>
        /// <param name="radius">Initial value of the Radius property.</param>
        public static intfStops CreateintfStops(global::System.Int32 id, global::System.String stopId, global::System.String stopIdNum, global::System.Int32 radius)
        {
            intfStops intfStops = new intfStops();
            intfStops.Id = id;
            intfStops.StopId = stopId;
            intfStops.StopIdNum = stopIdNum;
            intfStops.Radius = radius;
            return intfStops;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StopId
        {
            get
            {
                return _StopId;
            }
            set
            {
                OnStopIdChanging(value);
                ReportPropertyChanging("StopId");
                _StopId = StructuralObject.SetValidValue(value, false, "StopId");
                ReportPropertyChanged("StopId");
                OnStopIdChanged();
            }
        }
        private global::System.String _StopId;
        partial void OnStopIdChanging(global::System.String value);
        partial void OnStopIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, "Latitude");
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Double> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, "Longitude");
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Double> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Double> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true, "Description");
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SaeivId
        {
            get
            {
                return _SaeivId;
            }
            set
            {
                OnSaeivIdChanging(value);
                ReportPropertyChanging("SaeivId");
                _SaeivId = StructuralObject.SetValidValue(value, true, "SaeivId");
                ReportPropertyChanged("SaeivId");
                OnSaeivIdChanged();
            }
        }
        private global::System.String _SaeivId;
        partial void OnSaeivIdChanging(global::System.String value);
        partial void OnSaeivIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlaceName
        {
            get
            {
                return _PlaceName;
            }
            set
            {
                OnPlaceNameChanging(value);
                ReportPropertyChanging("PlaceName");
                _PlaceName = StructuralObject.SetValidValue(value, true, "PlaceName");
                ReportPropertyChanged("PlaceName");
                OnPlaceNameChanged();
            }
        }
        private global::System.String _PlaceName;
        partial void OnPlaceNameChanging(global::System.String value);
        partial void OnPlaceNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StopIdNum
        {
            get
            {
                return _StopIdNum;
            }
            set
            {
                OnStopIdNumChanging(value);
                ReportPropertyChanging("StopIdNum");
                _StopIdNum = StructuralObject.SetValidValue(value, false, "StopIdNum");
                ReportPropertyChanged("StopIdNum");
                OnStopIdNumChanged();
            }
        }
        private global::System.String _StopIdNum;
        partial void OnStopIdNumChanging(global::System.String value);
        partial void OnStopIdNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Radius
        {
            get
            {
                return _Radius;
            }
            set
            {
                OnRadiusChanging(value);
                ReportPropertyChanging("Radius");
                _Radius = StructuralObject.SetValidValue(value, "Radius");
                ReportPropertyChanged("Radius");
                OnRadiusChanged();
            }
        }
        private global::System.Int32 _Radius;
        partial void OnRadiusChanging(global::System.Int32 value);
        partial void OnRadiusChanged();

        #endregion

    }

    #endregion

}
