//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliable_Agencies
    {
        public long Agency_ID { get; set; }
        public string Agency_Prefix { get; set; }
        public string Agency_Name { get; set; }
        public string Agency_URL { get; set; }
        public string Agency_Phone { get; set; }
        public string Logo_Icon_URL { get; set; }
        public string Trip_Planner_URL { get; set; }
        public Nullable<int> RT_Type { get; set; }
        public string RT_URL { get; set; }
    }
}
