//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bike_Stations
    {
        public long Bike_Station_ID { get; set; }
        public string Name { get; set; }
        public string Terminal_Name { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geom { get; set; }
        public int Total { get; set; }
        public int Avaliable { get; set; }
        public System.DateTime Update_Time { get; set; }
        public long Genral_Agency_ID { get; set; }
        public int Renting { get; set; }
        public int Returning { get; set; }
        public string Additional_Info { get; set; }
        public System.DateTime Server_Update_Time { get; set; }
    }
}
