//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPI_Public_Transport_Entities : DbContext
    {
        public BPI_Public_Transport_Entities()
            : base("name=BPI_Public_Transport_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bike_Stations> Bike_Stations { get; set; }
        public virtual DbSet<Bus_Talk_Items> Bus_Talk_Items { get; set; }
        public virtual DbSet<Bus_Talk_Reports> Bus_Talk_Reports { get; set; }
        public virtual DbSet<Physical_Stops> Physical_Stops { get; set; }
        public virtual DbSet<PIS_Tickers> PIS_Tickers { get; set; }
        public virtual DbSet<Planned_Missions> Planned_Missions { get; set; }
        public virtual DbSet<Real_Time_Monitoring> Real_Time_Monitoring { get; set; }
        public virtual DbSet<Service_Dates> Service_Dates { get; set; }
        public virtual DbSet<Vehicles_Positions> Vehicles_Positions { get; set; }
        public virtual DbSet<General_Items_Agencies> General_Items_Agencies { get; set; }
        public virtual DbSet<Planned_Missions_Details> Planned_Missions_Details { get; set; }
        public virtual DbSet<Public_Transport_Routes> Public_Transport_Routes { get; set; }
        public virtual DbSet<Public_Transport_Routes_Details> Public_Transport_Routes_Details { get; set; }
        public virtual DbSet<Real_Time_Announcments> Real_Time_Announcments { get; set; }
        public virtual DbSet<Service_Enumarotrs> Service_Enumarotrs { get; set; }
        public virtual DbSet<User_Public_Transport_Favorites> User_Public_Transport_Favorites { get; set; }
    }
}
