//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPI_Public_Transport_CollectingEntities : DbContext
    {
        public BPI_Public_Transport_CollectingEntities()
            : base("name=BPI_Public_Transport_CollectingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Questionary_Report> Questionary_Report { get; set; }
        public virtual DbSet<Device_Positions> Device_Positions { get; set; }
        public virtual DbSet<Questionary_Report_Items> Questionary_Report_Items { get; set; }
    }
}
