//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device_Positions
    {
        public long IDX { get; set; }
        public int Device_Type { get; set; }
        public string Device_ID { get; set; }
        public long Session_ID { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public double Heading { get; set; }
        public double Speed { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geom { get; set; }
        public System.DateTime Device_Time { get; set; }
        public System.DateTime Insert_Time { get; set; }
        public bool IS_Foreign { get; set; }
        public Nullable<System.DateTime> Process_Time { get; set; }
    }
}
