//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class General_Items_Agencies
    {
        public long Genral_Agency_ID { get; set; }
        public string Name { get; set; }
        public string Logo_URL { get; set; }
        public string Description { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
