//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile_Apps_Config
    {
        public long Settings_ID { get; set; }
        public long App_ID { get; set; }
        public string Default_Agency { get; set; }
        public Nullable<int> Default_Radius { get; set; }
        public Nullable<bool> Deals { get; set; }
        public Nullable<bool> PIS { get; set; }
        public Nullable<short> Collecting_Position_Internval { get; set; }
        public Nullable<short> Check_Near_By_Interval { get; set; }
        public string Trip_Planner_URL { get; set; }
    }
}
