//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Physical_Stops
    {
        public long Internal_Stop_ID { get; set; }
        public string stop_id { get; set; }
        public string stop_code { get; set; }
        public Nullable<int> parent_station { get; set; }
        public string stop_name { get; set; }
        public Nullable<int> stop_desc { get; set; }
        public Nullable<int> location_type { get; set; }
        public Nullable<double> stop_lat { get; set; }
        public Nullable<double> stop_lon { get; set; }
        public string wheelchair_boarding { get; set; }
        public System.Data.Entity.Spatial.DbGeography position { get; set; }
    }
}
