//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PIS_Tickers
    {
        public long Ticker_ID { get; set; }
        public Nullable<bool> Is_Master { get; set; }
        public Nullable<int> Ticker_Type { get; set; }
        public string Ticker_Text { get; set; }
        public string Tiker_Color { get; set; }
        public string Tiker_URL { get; set; }
        public bool Geo_Enabled { get; set; }
        public System.Data.Entity.Spatial.DbGeography Polygone { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> Finish_Time { get; set; }
        public bool IS_Valid { get; set; }
    }
}
