//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planned_Missions_Details
    {
        public long Internal_Schedule_ID { get; set; }
        public Nullable<int> Internal_Route_ID { get; set; }
        public Nullable<int> Internal_Parent_Route_ID { get; set; }
        public Nullable<long> Internal_Stop_ID { get; set; }
        public string route_id { get; set; }
        public string trip_direction { get; set; }
        public string stop_id { get; set; }
        public string arrival_time { get; set; }
        public string departure_time { get; set; }
        public string stop_headsign { get; set; }
        public Nullable<int> stop_sequence { get; set; }
    }
}
