//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Transport_Routes_Details
    {
        public long Internal_Route_ID { get; set; }
        public Nullable<int> Internal_Parent_Route_ID { get; set; }
        public string agency_id { get; set; }
        public string route_id { get; set; }
        public string nb_route_id { get; set; }
        public string route_type { get; set; }
        public string route_short_name { get; set; }
        public string route_long_name { get; set; }
        public string route_color { get; set; }
        public string route_text_color { get; set; }
        public string route_url { get; set; }
        public string trip_direction { get; set; }
        public string direction_description { get; set; }
        public string stop_headsign { get; set; }
        public Nullable<int> internal_Service_ID { get; set; }
        public string First_Exit_Time { get; set; }
        public string Last_Exit_Time { get; set; }
        public string Pattern_First_Exit_Time { get; set; }
        public string Pattenr_Last_Exit_Time { get; set; }
        public Nullable<int> Pattern_Exits_Count { get; set; }
        public string shape_id { get; set; }
        public int Stops_count { get; set; }
    }
}
