//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Transport_Routes
    {
        public long Internal_Route_ID { get; set; }
        public Nullable<int> Internal_Parent_Route_ID { get; set; }
        public string agency_id { get; set; }
        public string route_id { get; set; }
        public string nb_route_id { get; set; }
        public string route_type { get; set; }
        public string route_short_name { get; set; }
        public string route_long_name { get; set; }
        public string route_color { get; set; }
        public string route_text_color { get; set; }
        public string route_url { get; set; }
        public string trip_direction { get; set; }
        public Nullable<int> direction_description { get; set; }
    }
}
