//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Real_Time_Monitoring
    {
        public long Indexer { get; set; }
        public long Internal_Route_ID { get; set; }
        public long Internal_Stop_ID { get; set; }
        public int Stop_Sequence { get; set; }
        public string Trip_ID { get; set; }
        public System.DateTime ETA { get; set; }
        public System.DateTime Lat_Update_Time { get; set; }
    }
}
