//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Positions
    {
        public long Position_ID { get; set; }
        public long Session_ID { get; set; }
        public long App_ID { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public Nullable<double> Alt { get; set; }
        public Nullable<int> Bearing { get; set; }
        public Nullable<double> Speed { get; set; }
        public System.DateTime GPS_TS { get; set; }
        public System.DateTime Reported_TS { get; set; }
        public System.DateTime Update_TS { get; set; }
    }
}
