//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Position
    {
        public long Position_ID { get; set; }
        public long Session_ID { get; set; }
        public long Login_ID { get; set; }
        public System.DateTime User_Time { get; set; }
        public System.DateTime Update_Time { get; set; }
        public System.DateTime GPS_Time { get; set; }
        public double Lat { get; set; }
        public double Lon { get; set; }
        public double Alt { get; set; }
        public int Bearing { get; set; }
        public double Speed { get; set; }
    }
}
