//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuspasManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicles_Positions
    {
        public long IDX { get; set; }
        public string Device_ID { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Speed { get; set; }
        public string Trip_ID { get; set; }
        public string Route_ID { get; set; }
        public Nullable<long> Internal_Route_ID { get; set; }
        public System.Data.Entity.Spatial.DbGeography Geom { get; set; }
        public string For_Display { get; set; }
        public Nullable<System.DateTime> Device_Time { get; set; }
        public Nullable<System.DateTime> Insert_Time { get; set; }
    }
}
